### ISSUE TITLE
1.1 Version?

### ISSUE THREAD

**Issue by Tharn** [f851374a/Armor-Full-Coverage#1]
Hi,

I know this mod is super simple but a new version would be nice.
I tried to get it done myself but I'm too dumb for xml.

**Comment by f851374a** [comment]
Sorry, i had no idea that someone is actually using it :D.
I  almost updated it a while ago, but had one little thing unresolved and stuck there. Now i tried again and saw that it was not hard to fix.
Anyway, it is updated now.
